ex_ruby/frais_km/fraiskm/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  resources :companies
  resources :scales
  resources :travels
  resources :vehicles
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ex_ruby/frais_km/fraiskm/app/models/scale.rb
class Scale < ApplicationRecord
end

ex_ruby/frais_km/fraiskm/app/controllers/scales_controller.rb
class ScalesController < ApplicationController
  before_action :set_scale, only: [:show, :edit, :update, :destroy]

  # GET /scales
  # GET /scales.json
  def index
    @scales = Scale.all
  end

  # GET /scales/1
  # GET /scales/1.json
  def show
  end

  # GET /scales/new
  def new
    @scale = Scale.new
  end

  # GET /scales/1/edit
  def edit
  end

  # POST /scales
  # POST /scales.json
  def create
    @scale = Scale.new(scale_params)

    respond_to do |format|
      if @scale.save
        format.html { redirect_to @scale, notice: 'Scale was successfully created.' }
        format.json { render :show, status: :created, location: @scale }
      else
        format.html { render :new }
        format.json { render json: @scale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scales/1
  # PATCH/PUT /scales/1.json
  def update
    respond_to do |format|
      if @scale.update(scale_params)
        format.html { redirect_to @scale, notice: 'Scale was successfully updated.' }
        format.json { render :show, status: :ok, location: @scale }
      else
        format.html { render :edit }
        format.json { render json: @scale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scales/1
  # DELETE /scales/1.json
  def destroy
    @scale.destroy
    respond_to do |format|
      format.html { redirect_to scales_url, notice: 'Scale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scale
      @scale = Scale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scale_params
      params.require(:scale).permit(:year, :vehicle_type, :power, :coefficient)
    end
end

ex_ruby/frais_km/fraiskm/app/helpers/scales_helper.rb
module ScalesHelper
end

ex_ruby/frais_km/fraiskm/app/views/scales/_form.html.erb
<%= form_with(model: scale, local: true) do |form| %>
  <% if scale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scale.errors.count, "error") %> prohibited this scale from being saved:</h2>

      <ul>
      <% scale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.date_select :year %>
  </div>

  <div class="field">
    <%= form.label :vehicle_type %>
    <%= form.text_field :vehicle_type %>
  </div>

  <div class="field">
    <%= form.label :power %>
    <%= form.text_area :power %>
  </div>

  <div class="field">
    <%= form.label :coefficient %>
    <%= form.text_field :coefficient %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ex_ruby/frais_km/fraiskm/app/views/scales/edit.html.erb
<h1>Editing Scale</h1>

<%= render 'form', scale: @scale %>

<%= link_to 'Show', @scale %> |
<%= link_to 'Back', scales_path %>

ex_ruby/frais_km/fraiskm/app/views/scales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scales</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Vehicle type</th>
      <th>Power</th>
      <th>Coefficient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scales.each do |scale| %>
      <tr>
        <td><%= scale.year %></td>
        <td><%= scale.vehicle_type %></td>
        <td><%= scale.power %></td>
        <td><%= scale.coefficient %></td>
        <td><%= link_to 'Show', scale %></td>
        <td><%= link_to 'Edit', edit_scale_path(scale) %></td>
        <td><%= link_to 'Destroy', scale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scale', new_scale_path %>

ex_ruby/frais_km/fraiskm/app/views/scales/new.html.erb
<h1>New Scale</h1>

<%= render 'form', scale: @scale %>

<%= link_to 'Back', scales_path %>

ex_ruby/frais_km/fraiskm/app/views/scales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @scale.year %>
</p>

<p>
  <strong>Vehicle type:</strong>
  <%= @scale.vehicle_type %>
</p>

<p>
  <strong>Power:</strong>
  <%= @scale.power %>
</p>

<p>
  <strong>Coefficient:</strong>
  <%= @scale.coefficient %>
</p>

<%= link_to 'Edit', edit_scale_path(@scale) %> |
<%= link_to 'Back', scales_path %>